language: cpp

matrix:
  include:
    - os: linux
      - compiler: gcc
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-7
        env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - compiler: clang
        addons:
          apt:
            sources:
              - llvm-toolchain-trusty-5.0
            packages:
              - clang-5.0
        env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode8
      - compiler: gcc
        env:
          - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
      - compiler: clang
        env:
          - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

before_script:
  - make clean

script:
  - make test
