language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8
      compiler: gcc
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - make clean

script:
  - make test
